[package]
name = "ridiculous_bevy_hot_reloading"
version = "0.1.0"
edition = "2021"


[dependencies]
hot_reloading_macros = { path = "macros", features = [] } 

[features]
bypass = ["hot_reloading_macros/bypass"]